#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [_QWERTY]     = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU)   ,  ENCODER_CCW_CW(KC_PGUP, KC_PGDN)   },
    [_GAME]       = { ENCODER_CCW_CW(VILL, VILL5)        ,  ENCODER_CCW_CW(KC_PGUP, KC_PGDN)   },
    [_COLEMAK_DH] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU)   ,  ENCODER_CCW_CW(KC_PGUP, KC_PGDN)   },
    [_LOWER]      = { ENCODER_CCW_CW(KC_LEFT, KC_RIGHT)  ,  ENCODER_CCW_CW(KC_VOLD, KC_VOLU)   },
    [_RAISE]      = { ENCODER_CCW_CW(S(KC_F3), KC_F3)    ,  ENCODER_CCW_CW(KC_LEFT, KC_RIGHT)  },
    [_NAV]        = { ENCODER_CCW_CW(KC_LEFT, KC_RIGHT)  ,  ENCODER_CCW_CW(KC_RIGHT, KC_LEFT)  },
    [_FUNCTION]   = { ENCODER_CCW_CW(XXXXXXX, XXXXXXX)   ,  ENCODER_CCW_CW(XXXXXXX, XXXXXXX)   },
    [_NUM]        = { ENCODER_CCW_CW(KC_LEFT, KC_RIGHT)  ,  ENCODER_CCW_CW(C(KC_Z), C(KC_Y))   },
    [_GAMELOW]    = { ENCODER_CCW_CW(XXXXXXX, XXXXXXX)   ,  ENCODER_CCW_CW(XXXXXXX, XXXXXXX)   },
    [_MOUSE]      = { ENCODER_CCW_CW(XXXXXXX, XXXXXXX)   ,  ENCODER_CCW_CW(KC_WH_U, KC_WH_D)   },
    [_ADJUST]     = { ENCODER_CCW_CW(XXXXXXX, XXXXXXX)   ,  ENCODER_CCW_CW(XXXXXXX, XXXXXXX)   },
};
#endif
